### ISSUE TITLE
Bug: GitLab CI pipeline fails unexpectedly for QDD 0.2.4

### ISSUE THREAD

**Issue by marcosdiezgarcia** [Fujitsu-UTokyo-QDD/QDD#70]
Jobs get unexpectedly and abruptly killed by the GitLab runner due to some incompatibility or misconfiguration between [QDD](https://github.com/Fujitsu-UTokyo-QDD/QDD) and the GitLab CI runner.

To reproduce the error I created a new GitLab repository for testing purposes and configured a `gitlab-ci.yml` file which does the following:
1. Creates an ubuntu 24.04 image and automatically installs some preliminary commands like git, python 3.12 and cmake >= 3.25.
2. Git clones QDD official repository.
3. Creates a Python 3.12 virtual environment and installs QDD from source (following QDD install instructions).
4. Shows successful installation of `qdd-0.2.4`.
5. Runs `python -c "import qdd"`

The output to stdout is the following:
> /usr/bin/bash: line 162:  5658 Killed                  python -c "import qdd"

However, pytket-qdd and qdd run without issue when installed locally via pytket-qdd Makefile (tested on GNU/Linux Ubuntu 22.04).

gitlab-ci.yaml
```
default:
    image: ubuntu:latest
    before_script:
        - apt-get update --yes
        - apt-get install --yes python3-pip python3-build python3-virtualenv cmake git
        - virtualenv venv
        - source venv/bin/activate
        - git clone https://github.com/Fujitsu-UTokyo-QDD/QDD.git
        - cd QDD
        - bash ./scripts/local_build_and_test_new.sh build
        - pip install .
        - cd -

stages:
    - test

job-test:
    stage: test
    script:
        - python --version
        - pip show -f qdd
        - python -c "print('This is a test')"
        - python -c "import qdd"
```

See attached GitLab runner log.

[20241022--gitlab-ci-qdd-log.txt](https://github.com/user-attachments/files/17539166/20241022--gitlab-ci-qdd-log.txt)
